import { notFound } from 'next/navigation';
import Link from 'next/link';
import { projects } from '@/lib/projects';
import { SiteHeader, SiteFooter } from '@/components/site-header';
import ProjectGallery from '@/components/project-gallery';
import ModelLaunch from '@/components/model-launch';
export function generateStaticParams(){return projects.map(p=>({slug:p.id}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=projects.find(p=>p.id===slug);return{title:p?`${p.title} — Omar Bacho`:'Project not found',description:p?.summary}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=await params;const p=projects.find(p=>p.id===slug);if(!p)return notFound();const index=projects.indexOf(p);const next=projects[(index+1)%projects.length];
 return <main id="top"><SiteHeader/><div className="project-heading"><Link className="back-link" href="/#work">← All projects</Link><div className="project-heading-row"><h1>{p.title}</h1><p>{p.category}<br/>{p.year}</p></div></div><div className="project-hero"><img src={p.hero} alt={p.images[0]?.alt||p.title} fetchPriority="high"/></div><section className="project-story"><div className="project-facts"><p className="eyebrow">Project information</p><dl>{[['Program',p.program],['Location',p.location],['Year',p.year],['Status',p.status],['Studio',p.office],['Contribution',p.role]].filter(([,v])=>v).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className="project-narrative"><p>{p.summary}</p>{p.credits&&<div className="project-credits"><span>Project team</span><p>{p.credits}</p></div>}{p.category==='Studio archive'&&<p className="credit-note">Included in the Amara studio portfolio. Design credits belong to the team listed above.</p>}{p.sourceLink&&<a className="text-link" href={p.sourceLink} target="_blank" rel="noreferrer">Project on the studio website ↗</a>}</div></section>{p.model&&<section className="project-model"><div><p className="eyebrow">Spatial study</p><h2>{p.model==='benina'?'A structure made to grow.':'One object. Many arrangements.'}</h2><p>{p.model==='benina'?'Explore the repeating bays, arch supports and circular roof openings.':'Separate the slatted panels and discover the triangular construction.'}</p></div><ModelLaunch model={p.model as 'benina'|'thing'}/></section>}<ProjectGallery project={p}/><section className="next-project"><span className="eyebrow">Next project</span><Link href={'/work/'+next.id}><h2>{next.title}</h2><span>↗</span></Link></section><SiteFooter/></main>
}
