import { notFound } from 'next/navigation';
import { projects } from '@/lib/projects';
import { SiteHeader, SiteFooter } from '@/components/site-header';
import ProjectGallery from '@/components/project-gallery';
import ModelLaunch from '@/components/model-launch';
import {modelCatalog,type ModelId} from '@/lib/model-catalog';
import {collections,collectionFor} from '@/lib/collections';
export function generateStaticParams(){return projects.map(p=>({slug:p.id}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=projects.find(p=>p.id===slug);return{title:p?`${p.title} — Omar Bacho`:'Project not found',description:p?.summary}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=await params;const p=projects.find(p=>p.id===slug);if(!p)return notFound();const peers=projects.filter(x=>x.category===p.category);const next=peers[(peers.indexOf(p)+1)%peers.length];const collection=collectionFor(p);const model=p.model?modelCatalog[p.model as ModelId]:null;
 return <main id="top"><SiteHeader/><div className="project-heading" id="main-content"><a className="back-link" href={"/work?category="+collection}>← {collections.find(c=>c.id===collection)?.label||"All projects"}</a><div className="project-heading-row"><h1>{p.title}</h1><p>{p.category}<br/>{p.year}</p></div></div><nav className="project-section-nav" aria-label="On this project"><a href="#overview">Overview</a><a href="#gallery">Gallery <span>{p.images.length}</span></a>{p.model&&<a href="#spatial-study">Explore in 3D ↗</a>}{p.sources.length>0&&<a href="#drawings">Original drawings</a>}</nav><div className="project-hero"><img src={p.hero} alt={p.images[0]?.alt||p.title} fetchPriority="high"/></div><section className="project-story" id="overview"><div className="project-facts"><p className="eyebrow">Project information</p><dl>{[['Program',p.program],['Location',p.location],['Year',p.year],['Status',p.status],['Studio',p.office],['Contribution',p.role]].filter(([,v])=>v).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className="project-narrative"><p>{p.summary}</p>{p.credits&&<div className="project-credits"><span>Project team</span><p>{p.credits}</p></div>}{p.category==='Studio archive'&&<p className="credit-note">Included in the Amara studio portfolio. Design credits belong to the team listed above.</p>}{p.sourceLink&&<a className="text-link" href={p.sourceLink} target="_blank" rel="noreferrer">Project on the studio website ↗</a>}</div></section>{p.model&&model&&<section className="project-model" id="spatial-study"><div><p className="eyebrow">Interactive study</p><h2>{model.subtitle}</h2><p>{model.description}</p></div><ModelLaunch model={p.model as ModelId}/></section>}<ProjectGallery project={p}/><section className="next-project"><span className="eyebrow">More in {collections.find(c=>c.id===collection)?.label||p.category}</span><a href={'/work/'+next.id}><h2>{next.title}</h2><span>↗</span></a></section><SiteFooter/></main>
}
