'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createBenina, createThing, disposeObject } from '@/lib/spatial-models';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import type { HandLandmarker } from '@mediapipe/tasks-vision';
type ViewerAPI={rotate:(x:number,y:number)=>void;zoom:(factor:number)=>void;reset:()=>void};
export default function ModelViewer({model}:{model:'benina'|'thing'}){
 const mount=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),tracker=useRef<HandLandmarker|null>(null),raf=useRef(0),alive=useRef(true),requestId=useRef(0),api=useRef<ViewerAPI|null>(null);
 const[explode,setExplode]=useState(0),[field,setField]=useState(true),[roof,setRoof]=useState(true),[camera,setCamera]=useState<'off'|'loading'|'on'>('off'),[status,setStatus]=useState(''),[renderError,setRenderError]=useState('');
 const settings=useRef({explode,roof});settings.current={explode,roof};
 function stopCamera(){requestId.current++;cancelAnimationFrame(raf.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;tracker.current?.close();tracker.current=null;if(video.current)video.current.srcObject=null;if(alive.current){setCamera('off');setStatus('')}}
 useEffect(()=>{alive.current=true;const hidden=()=>{if(document.hidden)stopCamera()};document.addEventListener('visibilitychange',hidden);return()=>{alive.current=false;document.removeEventListener('visibilitychange',hidden);stopCamera()}},[]);
 useEffect(()=>{
  const host=mount.current;if(!host)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch{setRenderError('3D is unavailable in this browser. The project drawings are available below.');return}
  setRenderError('');renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#edf0e9');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label',`${model==='benina'?'Benina structural':'Thing Flatpack'} 3D study. Drag to orbit, scroll to zoom. Keyboard controls are below.`);renderer.domElement.setAttribute('role','img');host.appendChild(renderer.domElement);
  const scene=new THREE.Scene();const camera3=new THREE.PerspectiveCamera(35,1,.1,150);const target=new THREE.Vector3(0,model==='benina'?2.6:1.9,0);const initial=model==='benina'?(field?new THREE.Vector3(17,13,20):new THREE.Vector3(10,9,12)):new THREE.Vector3(8,6,9);camera3.position.copy(initial);
  const controls=new OrbitControls(camera3,renderer.domElement);controls.target.copy(target);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=model==='benina'?5:3;controls.maxDistance=model==='benina'?45:23;controls.maxPolarAngle=Math.PI*.49;controls.enablePan=true;
  const study=model==='benina'?createBenina(field):createThing();scene.add(study.root);scene.add(new THREE.HemisphereLight('#ffffff','#b0ba9e',2.3));const sun=new THREE.DirectionalLight('#ffefd8',3);sun.position.set(10,17,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15});sun.shadow.bias=-.0003;scene.add(sun);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:'#e4e9dd',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.16;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(36,36,'#c9d1c1','#d6ddcf');grid.position.y=-.145;scene.add(grid);
  const resize=()=>{const{width,height}=host.getBoundingClientRect();renderer.setSize(width,height);camera3.aspect=width/Math.max(height,1);camera3.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();
  api.current={rotate(x,y){const offset=camera3.position.clone().sub(controls.target);const s=new THREE.Spherical().setFromVector3(offset);s.theta+=x;s.phi=THREE.MathUtils.clamp(s.phi+y,.12,Math.PI*.48);camera3.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(s));controls.update()},zoom(f){const d=camera3.position.clone().sub(controls.target);d.setLength(THREE.MathUtils.clamp(d.length()*f,controls.minDistance,controls.maxDistance));camera3.position.copy(controls.target).add(d);controls.update()},reset(){camera3.position.copy(initial);controls.target.copy(target);controls.update()}};
  let frame=0;function animate(){study.setExplode(settings.current.explode/100);study.setRoof(settings.current.roof);controls.update();renderer.render(scene,camera3);frame=requestAnimationFrame(animate)}animate();
  return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();disposeObject(scene);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();api.current=null}
 },[model,field]);
 async function startCamera(){
  if(!navigator.mediaDevices?.getUserMedia){setStatus('Camera gestures need a browser with camera access. Drag and zoom controls are ready to use.');return}
  const id=++requestId.current;setCamera('loading');setStatus('Preparing hand tracking…');
  try{
   const{FilesetResolver,HandLandmarker}=await import('@mediapipe/tasks-vision');const files=await FilesetResolver.forVisionTasks('/hand-tracking/wasm');const hand=await HandLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'/hand-tracking/hand_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.65,minTrackingConfidence:.6});
   if(!alive.current||id!==requestId.current){hand.close();return}tracker.current=hand;setStatus('Allow camera access to use hand gestures.');
   const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:640,height:480},audio:false});
   if(!alive.current||id!==requestId.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;const v=video.current;if(!v)throw new Error('Camera preview unavailable');v.srcObject=media;await v.play();if(!alive.current||id!==requestId.current)return;setCamera('on');setStatus('Show your hand to the camera.');
   let lastTime=-1,lastFrame=0,lastPoint:{x:number;y:number}|null=null,lastDistance:number|null=null,lastMessage='';
   const message=(s:string)=>{if(s!==lastMessage){lastMessage=s;setStatus(s)}};
   const loop=(now:number)=>{
    if(!alive.current||id!==requestId.current||!tracker.current)return;
    try{if(v.readyState>=2&&now-lastFrame>85&&v.currentTime!==lastTime){lastFrame=now;lastTime=v.currentTime;const hands=tracker.current.detectForVideo(v,now).landmarks;
     if(hands.length>=2){const a=hands[0][9],b=hands[1][9];const dist=Math.hypot(a.x-b.x,a.y-b.y);if(lastDistance&&dist>.06)api.current?.zoom(THREE.MathUtils.clamp(lastDistance/dist,.92,1.08));lastDistance=dist;lastPoint=null;message('Two hands detected · Move apart to zoom in.')}else if(hands.length===1){lastDistance=null;const h=hands[0];const palm=Math.hypot(h[0].x-h[9].x,h[0].y-h[9].y);const pinch=Math.hypot(h[4].x-h[8].x,h[4].y-h[8].y)<palm*.45;if(pinch){const point={x:h[8].x,y:h[8].y};if(lastPoint)api.current?.rotate((point.x-lastPoint.x)*-5,(point.y-lastPoint.y)*-3);lastPoint=point;message('Pinch held · Move your hand to rotate.')}else{lastPoint=null;message('Hand detected · Pinch thumb and index finger to rotate.')}}else{lastPoint=null;lastDistance=null;message('Looking for your hands…')}}
     raf.current=requestAnimationFrame(loop)
    }catch{stopCamera();setStatus('Hand tracking stopped. Try again, or use drag and zoom controls.')}
   };raf.current=requestAnimationFrame(loop);
  }catch(error){if(id!==requestId.current)return;stopCamera();if(alive.current)setStatus(error instanceof DOMException&&error.name==='NotAllowedError'?'Camera access was declined. You can still drag, rotate and zoom.':'Camera gestures could not start. Check camera availability, then try again.');}
 }
 return <div className="viewer"><div className="viewer-stage"><div className="three-mount" ref={mount}/>{renderError&&<div className="render-error">{renderError}</div>}<div className="view-label"><span>{model==='benina'?'BIA / Structural system':'THING / Assembly study'}</span><small>Approximate reconstruction</small></div><div className="view-instructions">Drag to rotate · Scroll or pinch to zoom</div><div className={'camera-preview '+(camera==='on'?'visible':'')}><video ref={video} muted playsInline autoPlay/><span>Camera on · Local processing</span></div></div><div className="viewer-toolbar"><div className="view-actions"><button onClick={()=>api.current?.rotate(-.25,0)} aria-label="Rotate model left">↶</button><button onClick={()=>api.current?.rotate(.25,0)} aria-label="Rotate model right">↷</button><button onClick={()=>api.current?.zoom(.85)} aria-label="Zoom in">+</button><button onClick={()=>api.current?.zoom(1.18)} aria-label="Zoom out">−</button><button onClick={()=>{api.current?.reset();setExplode(0);setRoof(true)}}>Reset</button></div><div className="model-options">{model==='benina'&&<label><Switch checked={field} onCheckedChange={setField}/>Roof field</label>}<label><Switch checked={roof} onCheckedChange={setRoof}/>{model==='benina'?'Roof slabs':'Top panel'}</label></div><div className="explode-control"><label htmlFor="explode-slider">Assembly <span>{explode===0?'Assembled':'Exploded'}</span></label><Slider id="explode-slider" aria-label="Separate model components" value={[explode]} onValueChange={v=>setExplode(Array.isArray(v)?v[0]:v)} min={0} max={100} step={1}/></div></div><div className="gesture-panel"><div><h3>Explore with your hands</h3><p>Pinch thumb + index finger and move to rotate. Move two hands apart to zoom.</p><p className="camera-privacy">Camera stays off until you enable it. Video is processed on your device and is not recorded or uploaded.</p></div><button className="camera-button" disabled={!!renderError} onClick={camera==='off'?startCamera:stopCamera}>{camera==='off'?'Enable hand gestures ↗':camera==='loading'?'Cancel camera setup':'Turn camera off'}</button>{status&&<p className="gesture-status" role="status">{status}</p>}</div></div>
}
