'use client';
import { useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { Project } from '@/lib/projects';
export default function ProjectGallery({project:p}:{project:Project}){
 const gallery=p.images.filter(im=>im.src!==p.hero);const[selected,setSelected]=useState<number|null>(null);const[showSheets,setShowSheets]=useState(false);const[showAll,setShowAll]=useState(false);
 const sheets=p.sources.flatMap(s=>s.pages.map(page=>({src:`/plates/${s.source}-${String(page).padStart(2,'0')}.jpg`,label:`${s.source==='omar'?'Omar Bacho':'Amara'} portfolio · page ${page}`})));
 const items=[...gallery.map(im=>({src:im.src,label:im.alt})),...(showSheets?sheets:[])];
 return <section className="gallery-section" id="gallery"><div className="gallery-section-heading"><h2>Project gallery</h2><span>{gallery.length} images</span></div><div className="gallery-grid">{(showAll?gallery:gallery.slice(0,6)).map((im,i)=><button className={'gallery-item '+(im.width/im.height>1.8?'gallery-wide':'')} key={im.src} onClick={()=>setSelected(i)} aria-label={`Enlarge ${im.alt}`}><img src={im.src} alt={im.alt} loading="lazy" decoding="async"/><span className="enlarge-icon" aria-hidden="true">↗</span></button>)}</div>{gallery.length>6&&<button className="gallery-expand" onClick={()=>setShowAll(!showAll)} aria-expanded={showAll}>{showAll?"Show fewer images":"View all "+gallery.length+" images"}<span>{showAll?"−":"+"}</span></button>}{sheets.length>0&&<div className="source-sheets" id="drawings"><button onClick={()=>setShowSheets(!showSheets)} aria-expanded={showSheets}>Original portfolio sheets <span>{sheets.length} pages {showSheets?'−':'+'}</span></button>{showSheets&&<div className="sheets-grid">{sheets.map((s,i)=><button key={s.src} onClick={()=>setSelected(gallery.length+i)}><img src={s.src} loading="lazy" alt={s.label}/><span>{s.label}</span></button>)}</div>}</div>}<Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="lightbox" showCloseButton><DialogTitle className="sr-only">{p.title} — image viewer</DialogTitle><DialogDescription className="sr-only">Use the previous and next buttons to browse project images.</DialogDescription>{selected!==null&&items[selected]&&<><img src={items[selected].src} alt={items[selected].label}/><div className="lightbox-controls"><button aria-label="Previous image" onClick={()=>setSelected((selected+items.length-1)%items.length)}>←</button><span>{selected+1} / {items.length}</span><button aria-label="Next image" onClick={()=>setSelected((selected+1)%items.length)}>→</button></div></>}</DialogContent></Dialog></section>
}
