export const modelCatalog={
 benina:{title:'Benina International Airport',project:'benina-international-airport',subtitle:'Modular roof & daylight',image:'/images/omar-34-0.webp',description:'Follow the structural bay from slender columns to arch supports and roof openings.',layer:'Roof slabs',action:'',max:100,unit:'',source:'Omar Bacho portfolio, pp. 34–35',explore:'Select an arch or roof slab to see how the bay comes together.'},
 thing:{title:'Thing Flatpack',project:'thing',subtitle:'Furniture & assembly',image:'/images/omar-39-3.webp',description:'Separate the slatted timber panels, triangular shelf and slender support.',layer:'Top panel',action:'',max:100,unit:'',source:'Omar Bacho portfolio, pp. 37–39',explore:'Select a panel to understand the triangular assembly.'},
 landship:{title:'Landship',project:'landship',subtitle:'Cabin, frames & programme',image:'/images/omar-28-0.webp',description:'Explore repeated ribs, a level timber floor, fitted modules and opening glazing.',layer:'Glazing',action:'Open glazing',max:15,unit:'°',source:'Omar Bacho portfolio, pp. 28–29',explore:'Hide the glazing to see the furnished modules between the ribs.'},
 studio:{title:'Artist’s Studio Balcony',project:'artists-studio-balcony',subtitle:'Lattice, storage & canopy',image:'/images/1ZSOSYCURbpGjcGKIK5MjfPWX90BHZHcB.webp',description:'Inspect the carved storage grid and the curved ribs that turn a wall into a canopy.',layer:'Canopy',action:'',max:100,unit:'',source:'Omar Bacho portfolio, pp. 12–13; Artists Home drawings',explore:'Select the storage grid or curved canopy to inspect its construction.'},
 twig:{title:'Lebanese Concept House',project:'lebanese-concept-house',subtitle:'Twig kit / joints & display',image:'/images/amara-23-0.webp',description:'Look closely at the weighted feet, paired timber rails and removable display surfaces.',layer:'Display surfaces',action:'Lift platforms',max:100,unit:'%',source:'Omar Bacho portfolio, pp. 8–9',explore:'Separate the assembly to expose the platform locating blocks and bolts.'},
 parc:{title:'Résidence du Parc',project:'residence-du-parc',subtitle:'Portal & sliding-screen study',image:'/images/1UqH72f-0SKkyhjZTsMKnbcvYhxiKDP_o.webp',description:'Move through a study of coloured portals, curved openings and a full-height sliding screen.',layer:'Screen',action:'Open screen',max:100,unit:'%',source:'Omar Bacho portfolio, pp. 22–23',explore:'Slide the screen to see how two spaces connect. This is a detail study, not the full apartment.'},
};
export type ModelId=keyof typeof modelCatalog;
export const modelIds=Object.keys(modelCatalog) as ModelId[];
