import * as THREE from 'three';
export type StudyPart={id:string;label:string;detail:string;node:THREE.Object3D};
export type StudyModel={root:THREE.Group;parts:StudyPart[];setExplode:(n:number)=>void;setRoof:(visible:boolean)=>void;setDetail?:(n:number)=>void};
function part(id:string,label:string,detail:string,node:THREE.Object3D):StudyPart{node.userData.partId=id;return{id,label,detail,node}}
function material(color:string){return new THREE.MeshStandardMaterial({color,roughness:.78,metalness:.04})}
function box(group:THREE.Group,size:number[],pos:number[],mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(...size as [number,number,number]),mat);m.position.set(...pos as [number,number,number]);m.castShadow=true;m.receiveShadow=true;group.add(m);return m}
function beam(group:THREE.Group,a:THREE.Vector3,b:THREE.Vector3,w:number,d:number,mat:THREE.Material){const m=box(group,[w,a.distanceTo(b),d],a.clone().add(b).multiplyScalar(.5).toArray(),mat);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());return m}
export function createBenina(field:boolean):StudyModel{
 const root=new THREE.Group();const steel=material('#aeb6ae');const concrete=material('#eeede3');const columns=new THREE.Group(),arches=new THREE.Group(),roof=new THREE.Group(),glazing=new THREE.Group(),beams=new THREE.Group();root.add(columns,arches,beams,roof,glazing);
 const nx=field?3:1,nz=field?2:1,B=4,H=4,ox=-nx*B/2,oz=-nz*B/2;
 for(let x=0;x<=nx;x++)for(let z=0;z<=nz;z++)box(columns,[.13,2.15,.13],[ox+x*B,1.075,oz+z*B],steel);
 function arch(x:number,z:number,rot:number){const shape=new THREE.Shape();shape.moveTo(0,3.68);shape.lineTo(B,3.68);shape.lineTo(B,2.0);for(let j=0;j<=40;j++){const t=Math.PI*j/40;shape.lineTo(B/2+B/2*Math.cos(t),2+1.55*Math.sin(t))}shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:.07,bevelEnabled:false});const mesh=new THREE.Mesh(geo,steel);mesh.position.set(x,0,z);mesh.rotation.y=rot;mesh.castShadow=true;arches.add(mesh)}
 for(let x=0;x<nx;x++)for(let z=0;z<=nz;z++){arch(ox+x*B,oz+z*B,0);box(beams,[B,.18,.15],[ox+(x+.5)*B,3.8,oz+z*B],steel)}
 for(let x=0;x<=nx;x++)for(let z=0;z<nz;z++){arch(ox+x*B,oz+z*B,-Math.PI/2);box(beams,[.15,.18,B],[ox+x*B,3.8,oz+(z+.5)*B],steel)}
 for(let x=0;x<nx;x++)for(let z=0;z<nz;z++){
  const s=new THREE.Shape();s.moveTo(-1.94,-1.94);s.lineTo(1.94,-1.94);s.lineTo(1.94,1.94);s.lineTo(-1.94,1.94);s.closePath();const hole=new THREE.Path();hole.absarc(0,0,.46,0,Math.PI*2,true);s.holes.push(hole);
  const m=new THREE.Mesh(new THREE.ExtrudeGeometry(s,{depth:.31,bevelEnabled:false,curveSegments:40}),concrete);m.rotation.x=-Math.PI/2;m.position.set(ox+(x+.5)*B,3.84,oz+(z+.5)*B);m.castShadow=true;m.receiveShadow=true;roof.add(m);
  const g=new THREE.Mesh(new THREE.CircleGeometry(.44,48),new THREE.MeshPhysicalMaterial({color:'#b6d1d1',roughness:.1,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}));g.rotation.x=-Math.PI/2;g.position.set(m.position.x,4.18,m.position.z);glazing.add(g);
 }
 return{root,parts:[part('columns','Corner columns','Slender columns sit at the corners of each bay, keeping its centre open.',columns),part('arches','Arch supports','Curved steel supports meet between columns to form arches in both directions.',arches),part('beams','Perimeter beams','Horizontal members link the repeated structural units.',beams),part('roof','Precast roof slabs','A circular opening is cut through each square roof module.',roof),part('glazing','Skylights','Roof openings bring diffuse light into the terminal.',glazing)],setExplode(n){arches.position.y=n*.85;beams.position.y=n*1.6;roof.position.y=n*2.8;glazing.position.y=n*3.4},setRoof(v){roof.visible=v;glazing.visible=v}};
}
export function createThing():StudyModel{
 const root=new THREE.Group();root.scale.setScalar(3.7);root.position.set(-1.85,.05,-1.85);const wood=['#b98d59','#c29a68','#cfa976','#d5b382','#c4a273'].map(material);const dark=material('#2e3230');const spine=new THREE.Group(),top=new THREE.Group(),bottom=new THREE.Group(),shelf=new THREE.Group(),rod=new THREE.Group();root.add(spine,top,bottom,shelf,rod);
 for(let i=0;i<11;i++)box(spine,[.056,1,.036],[.032+i*.093,0.5,0],wood[i%wood.length]);
 box(spine,[1.04,.038,.06],[.5,0,0],wood[2]);box(spine,[1.04,.038,.06],[.5,1,0],wood[1]);
 function triangle(g:THREE.Group,y:number){for(let i=0;i<11;i++){const x=.025+i*.09;const l=1-x;box(g,[.054,.035,l],[x,y,l/2],wood[(i+2)%wood.length])}beam(g,new THREE.Vector3(0,y,0),new THREE.Vector3(0,y,1),.037,.043,wood[0]);beam(g,new THREE.Vector3(0,y,1),new THREE.Vector3(1,y,0),.037,.043,wood[2]);beam(g,new THREE.Vector3(0,y,0),new THREE.Vector3(1,y,0),.037,.043,wood[1])}
 triangle(top,1);triangle(bottom,0);
 const shape=new THREE.Shape();shape.moveTo(.03,.03);shape.lineTo(.89,.03);shape.lineTo(.03,.89);shape.closePath();const plane=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.015,bevelEnabled:false}),dark);plane.rotation.x=Math.PI/2;plane.position.y=.47;shelf.add(plane);
 const leg=new THREE.Mesh(new THREE.CylinderGeometry(.01,.01,1,12),dark);leg.position.set(.025,.5,.965);rod.add(leg);
 for(const pos of [[.02,1,.98],[.98,1,.02],[.02,0,.98]]){const bolt=new THREE.Mesh(new THREE.SphereGeometry(.012,10,8),dark);bolt.position.set(...pos as [number,number,number]);root.add(bolt)}
 return{root,parts:[part('spine','Slatted spine','Timber strips create a rigid upright with open gaps.',spine),part('top','Triangular top','Progressively shorter strips follow the triangular footprint.',top),part('bottom','Lower panel','A second slatted panel completes the assembly.',bottom),part('shelf','Shelf insert','A thin dark shelf sits between the timber spine and outer support.',shelf),part('rod','Support rod','A slender dark rod supports the free corner.',rod)],setExplode(n){top.position.y=n*.5;bottom.position.y=-n*.05;spine.position.z=-n*.35;rod.position.x=-n*.25;rod.position.z=n*.25;shelf.position.x=n*.45;shelf.position.z=n*.45},setRoof(v){top.visible=v}};
}
export function disposeObject(root:THREE.Object3D){const mats=new Set<THREE.Material>();root.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m))}});mats.forEach(m=>m.dispose())}
export function createLandship():StudyModel{
 const root=new THREE.Group(),piles=new THREE.Group(),floor=new THREE.Group(),ribs=new THREE.Group(),modules=new THREE.Group(),glass=new THREE.Group(),ramps=new THREE.Group();root.add(piles,floor,ribs,modules,glass,ramps);
 const timber=material('#bda17b'),dark=material('#394039'),lining=material('#dfd0b7'),fabric=material('#d7ddcf');const glazing=new THREE.MeshPhysicalMaterial({color:'#bad3d1',transparent:true,opacity:.16,roughness:.12,side:THREE.DoubleSide,depthWrite:false});
 const length=12.8,base=.85,w=2.5,N=17;const panels:THREE.Mesh[]=[];
 function profile(t:number){const k=Math.sin(Math.PI*t);return [[-w/2,base],[w/2,base],[w/2,base+2.25],[-.75+1.5*t,base+2.5+k*.85],[-w/2,base+2.3]]}
 for(let i=0;i<N;i++){const z=-length/2+i*.8,pts=profile(i/(N-1));for(let j=0;j<pts.length;j++){const a=pts[j],b=pts[(j+1)%pts.length];beam(ribs,new THREE.Vector3(a[0],a[1],z),new THREE.Vector3(b[0],b[1],z),.11,.13,dark)}
 if(i%2===0)for(const x of [-.9,.9]){box(piles,[.075,.7,.075],[x,.35,z],dark);for(let r=0;r<2;r++){const disc=new THREE.Mesh(new THREE.CylinderGeometry(.14,.14,.025,12),dark);disc.position.set(x,.1+r*.12,z);piles.add(disc)}}
 if(i<N-1){const p=profile((i+.5)/(N-1));for(const side of [-1,1]){const pane=new THREE.Mesh(new THREE.PlaneGeometry(.66,1.7),glazing);pane.position.set(side*1.255,base+1.1,z+.4);pane.rotation.y=Math.PI/2;glass.add(pane);panels.push(pane)}const a=p[2],b=p[3],c=p[4];for(const [v1,v2] of [[a,b],[b,c]]){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([v1[0],v1[1],z+.08,v2[0],v2[1],z+.08,v2[0],v2[1],z+.72,v1[0],v1[1],z+.72],3));g.setIndex([0,1,2,0,2,3]);g.computeVertexNormals();glass.add(new THREE.Mesh(g,glazing))}}
 }
 box(floor,[w,.16,length],[0,base-.1,0],timber);for(let x=-1.2;x<=1.2;x+=.15)box(floor,[.004,.005,length],[x,base-.015,0],dark);for(const x of [-.85,.85])box(floor,[.14,.24,length],[x,base-.3,0],dark);
 for(let i=1;i<15;i++){const z=-length/2+(i+.5)*.8;if(i<=3){box(modules,[.6,.36,.65],[-.84,base+.18,z],timber);box(modules,[.63,.075,.63],[-.84,base+.4,z],fabric)}else if(i<=5){box(modules,[.82,2.0,.71],[-.78,base+1,z],lining);box(modules,[.012,1.75,.01],[-.355,base+1,z],dark)}else if(i<=7){box(modules,[.6,.85,.73],[-.85,base+.425,z],timber);box(modules,[.64,.035,.76],[-.85,base+.86,z],lining);if(i===7)box(modules,[.4,.02,.4],[-.85,base+.885,z],dark)}else{box(modules,[.65,.42,.7],[-.8,base+.21,z],timber);box(modules,[.63,.09,.65],[-.8,base+.465,z],fabric);box(modules,[.22,.045,.67],[1.05,base+1.7,z],timber)}}
 for(const side of [-1,1]){const ramp=box(ramps,[1,.08,1.5],[0,base*.5,side*(length/2+.65)],timber);ramp.rotation.x=side*.48;for(const x of [-.48,.48])beam(ramps,new THREE.Vector3(x,base,side*length/2),new THREE.Vector3(x,.1,side*(length/2+1.4)),.055,.055,dark)}
 return{root,parts:[part('piles','Screw piles','Slender supports hold a level floor above the terrain.',piles),part('floor','Keel & floor','A continuous prefabricated base carries the repeated modules.',floor),part('ribs','Repeated ribs','Changing upper profiles form the cabin while its floor remains level.',ribs),part('modules','Fitted modules','Seating, services and sleeping elements fit between the ribs, beside a clear passage.',modules),part('glazing','Opening glazing','The portfolio describes individual glass panels opening up to 15 degrees.',glass),part('ramps','Entrance ramps','Ramps connect the raised cabin to the ground at each end.',ramps)],setExplode(n){floor.position.y=n*.35;ribs.position.y=n*1.3;modules.position.x=-n*2.2;glass.position.x=n*2.3;ramps.position.z=n*1.1},setRoof(v){glass.visible=v},setDetail(n){panels.forEach((p,i)=>{p.rotation.z=(i%2?1:-1)*THREE.MathUtils.degToRad(n)})}};
}
export function createTwig():StudyModel{
 const root=new THREE.Group();root.scale.setScalar(2.8);const feet=new THREE.Group(),stems=new THREE.Group(),rails=new THREE.Group(),fasteners=new THREE.Group(),surfaces=new THREE.Group();root.add(feet,stems,rails,fasteners,surfaces);
 const wood=material('#cfb48a'),concrete=material('#b8b8ab'),cap=material('#8c9287'),silver=new THREE.MeshStandardMaterial({color:'#9ba3a0',metalness:.8,roughness:.32}),white=material('#f4f3eb');
 const pts=[[-1.3,-.7],[-.45,-.7],[.4,-.7],[.4,.15],[1.25,.15],[1.25,1.0]];const heights=[1.35,1.35,1.35,1.0,1.0,1.6];
 for(let i=0;i<pts.length;i++){const[x,z]=pts[i];const foot=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,.4,24),concrete);foot.position.set(x,.2,z);foot.castShadow=true;feet.add(foot);box(stems,[.06,heights[i],.06],[x,heights[i]/2+.2,z],wood);box(stems,[.061,.004,.061],[x,heights[i]+.202,z],cap)}
 for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],xdir=a[0]!==b[0],h=Math.min(heights[i],heights[i+1])+.08,mid=new THREE.Vector3((a[0]+b[0])/2,h,(a[1]+b[1])/2);
 for(const side of [-1,1]){const off=side*.0475;const m=box(rails,xdir?[1.07,.05,.025]:[.025,.05,1.07],[mid.x+(xdir?0:off),h,mid.z+(xdir?off:0)],wood);for(const end of [-1,1])box(rails,xdir?[.004,.051,.026]:[.026,.051,.004],[m.position.x+(xdir?end*.535:0),h,m.position.z+(xdir?0:end*.535)],cap);
 for(const point of [a,b]){const bolt=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,.008,12),silver);bolt.position.set(point[0]+(xdir?0:side*.064),h,point[1]+(xdir?side*.064:0));bolt.rotation[xdir?'x':'z']=Math.PI/2;fasteners.add(bolt)}}
 const platform=new THREE.Group();platform.position.copy(mid);let geometry:THREE.BufferGeometry;if(i%3===0)geometry=new THREE.CylinderGeometry(.27,.27,.025,40);else if(i%3===1)geometry=new THREE.BoxGeometry(.5,.025,.5);else{const s=new THREE.Shape();s.moveTo(-.3,-.24);s.lineTo(.3,-.24);s.lineTo(0,.3);s.closePath();geometry=new THREE.ExtrudeGeometry(s,{depth:.025,bevelEnabled:false});geometry.rotateX(-Math.PI/2)}const top=new THREE.Mesh(geometry,white);top.position.y=.045;top.castShadow=true;platform.add(top);box(platform,xdir?[.19,.065,.04]:[.04,.065,.19],[0,0,0],wood);surfaces.add(platform)}
 return{root,parts:[part('feet','Concrete feet','Cylindrical ballast stabilises the freestanding display system.',feet),part('stems','Timber stems','Square uprights carry branches at different heights.',stems),part('rails','Paired branches','Two rails clamp either side of each stem, with gray-painted ends.',rails),part('bolts','Bolted joints','Visible fasteners join the paired rails to each timber stem.',fasteners),part('platforms','Removable platforms','Circle, square and triangle tops have underside blocks that locate between the rails.',surfaces)],setExplode(n){stems.position.y=n*.2;rails.position.y=n*.45;fasteners.position.x=n*.15;surfaces.position.y=n*.75},setRoof(v){surfaces.visible=v},setDetail(n){surfaces.children.forEach(c=>c.position.y+=(n/100-(c.userData.lastLift||0))*.4);surfaces.children.forEach(c=>c.userData.lastLift=n/100)}};
}
// Keep the dense lattice responsive by drawing repeated members as instances.
function instanceRepeatedMembers(group:THREE.Group){
 const batches=new Map<string,THREE.Mesh[]>();
 for(const child of [...group.children]){if(!(child instanceof THREE.Mesh)||!(child.geometry instanceof THREE.BoxGeometry)||Array.isArray(child.material))continue;
 const p=child.geometry.parameters;const key=[p.width,p.height,p.depth].map(n=>n.toFixed(5)).join(':')+child.material.uuid;const batch=batches.get(key)||[];batch.push(child);batches.set(key,batch)}
 for(const meshes of batches.values()){if(meshes.length<4)continue;const first=meshes[0],instanced=new THREE.InstancedMesh(first.geometry,first.material,meshes.length);instanced.castShadow=true;instanced.receiveShadow=true;
 meshes.forEach((m,i)=>{m.updateMatrix();instanced.setMatrixAt(i,m.matrix);group.remove(m);if(m.geometry!==first.geometry)m.geometry.dispose()});instanced.instanceMatrix.needsUpdate=true;instanced.computeBoundingBox();instanced.computeBoundingSphere();group.add(instanced)}
}
export function createStudio():StudyModel{
 const root=new THREE.Group(),grid=new THREE.Group(),canopy=new THREE.Group(),infill=new THREE.Group(),base=new THREE.Group();root.add(grid,canopy,infill,base);const steel=material('#dfe3d9'),plinth=material('#c9ccbe'),canvas=material('#efe8d7'),wood=material('#b19c7f');
 const x0=-3.5,m=.2,z0=-1.6;const openings=[[0,0,5,5],[6,0,3,6],[10,1,5,5],[2,7,3,3],[11,8,5,4],[16,2,3,5]];
 const carved=(x:number,y:number,vertical:boolean)=>openings.some(([a,b,w,h])=>vertical?x>a&&x<a+w&&y>=b&&y<b+h:y>b&&y<b+h&&x>=a&&x<a+w);
 for(const depth of [0,.35]){
 for(let x=0;x<=20;x++)for(let y=0;y<13;y++)if(!carved(x,y,true))box(grid,[.018,m,.018],[x0+x*m,.18+(y+.5)*m,z0+depth],steel);
 for(let y=0;y<=13;y++)for(let x=0;x<20;x++)if(!carved(x,y,false))box(grid,[m,.018,.018],[x0+(x+.5)*m,.18+y*m,z0+depth],steel);
 }
 for(let x=0;x<=20;x+=2)for(let y=0;y<=13;y+=2)box(grid,[.018,.018,.35],[x0+x*m,.18+y*m,z0+.175],steel);
 for(const[a,b,w,h]of openings){box(infill,[w*m-.035,.025,.35],[x0+(a+w/2)*m,.18+b*m,z0+.175],wood);const board=box(infill,[w*m*.65,h*m*.72,.028],[x0+(a+w/2)*m,.18+b*m+h*m*.39,z0+.18],canvas);board.rotation.x=-.08}
 for(let j=0;j<6;j++)box(infill,[.5,.018,.32],[x0+3.5,.4+j*.09,z0+.17],steel);
 for(let i=0;i<14;i++){const x=.75+i*.2;let prev=new THREE.Vector3(x,.18,-1.35);const path=[new THREE.Vector3(x,1.85,-1.35)];for(let j=1;j<=20;j++){const t=Math.PI-Math.PI/2*j/20;path.push(new THREE.Vector3(x,1.85+.8*Math.sin(t),-.55+.8*Math.cos(t)))}path.push(new THREE.Vector3(x,2.65,1.6));for(const p of path){beam(canopy,prev,p,.024,.024,steel);prev=p}}
 for(let z=-.55;z<=1.65;z+=.2)box(canopy,[2.7,.02,.02],[2.05,2.66,z],steel);box(base,[7.3,.16,3.6],[0,.05,0],plinth);box(base,[.1,.55,3.4],[3.6,.36,0],plinth);box(base,[3,.55,.1],[2.05,.36,1.75],plinth);
 instanceRepeatedMembers(grid);instanceRepeatedMembers(canopy);
 return{root,parts:[part('grid','Carved lattice','The 20×20 base grid opens into larger bays for canvases and easels. This pattern is interpretive.',grid),part('canopy','Curved canopy ribs','Closely spaced metal ribs turn vertical screening into an open overhead structure.',canopy),part('storage','Shelves & drying rack','Deep shelves and repeated trays turn the lattice into working storage.',infill),part('base','Balcony edge','A low parapet contains the open workspace.',base)],setExplode(n){grid.position.z=-n*.75;canopy.position.y=n*1.2;infill.position.z=n*.8},setRoof(v){canopy.visible=v}};
}
export function createParc():StudyModel{
 const root=new THREE.Group(),floor=new THREE.Group(),portals=new THREE.Group(),screen=new THREE.Group(),cabinet=new THREE.Group(),track=new THREE.Group();root.add(floor,portals,screen,cabinet,track);const white=material('#e9e7df'),wood=material('#ba9570'),dark=material('#394039');const colors=['#bba04f','#4c6477','#6b7b66'];
 box(floor,[5.8,.13,7.4],[0,0,0],material('#ddd4c1'));
 for(let i=0;i<3;i++){const s=new THREE.Shape();s.moveTo(-2.5,.06);s.lineTo(2.5,.06);s.lineTo(2.5,3.15);s.lineTo(-2.5,3.15);s.closePath();const hole=new THREE.Path();hole.moveTo(-.95,.055);hole.lineTo(-.95,1.85);hole.absarc(0,1.85,.95,Math.PI,0,true);hole.lineTo(.95,.055);hole.closePath();s.holes.push(hole);const mesh=new THREE.Mesh(new THREE.ExtrudeGeometry(s,{depth:.22,bevelEnabled:false,curveSegments:36}),white);mesh.position.z=-2.5+i*2.4;mesh.castShadow=true;portals.add(mesh);
 const reveal=new THREE.Group();const mat=material(colors[i]);for(const x of [-.95,.95])box(reveal,[.06,1.8,.26],[x,.95,mesh.position.z+.11],mat);const curve=new THREE.EllipseCurve(0,1.85,.95,.95,0,Math.PI,false,0).getPoints(40);for(let j=0;j<curve.length-1;j++)beam(reveal,new THREE.Vector3(curve[j].x,curve[j].y,mesh.position.z+.1),new THREE.Vector3(curve[j+1].x,curve[j+1].y,mesh.position.z+.1),.06,.27,mat);portals.add(reveal)}
 const panel=box(screen,[2.05,2.98,.065],[0,1.55,.12],wood);for(let i=0;i<18;i++)box(screen,[.014,2.9,.009],[-.93+i*.11,1.55,.16],dark);box(track,[4.6,.045,.055],[.8,3.09,.13],dark);box(track,[4.6,.025,.025],[.8,.08,.13],dark);
 box(cabinet,[.55,.55,5.8],[-2.6,.34,0],white);for(let z=-2.8;z<3;z+=.72)box(cabinet,[.53,2.2,.045],[-2.6,1.73,z],dark);for(let y=.65;y<2.9;y+=.55)box(cabinet,[.56,.035,5.8],[-2.6,y,0],dark);
 return{root,parts:[part('portals','Coloured portals','Curved openings and painted reveals mark successive spaces. Profiles are source-inspired.',portals),part('screen','Full-height screen','A sliding screen adjusts separation and continuity between rooms.',screen),part('track','Screen track','The panel moves alongside its opening; exact hardware is interpretive.',track),part('cabinet','Storage wall','Shelving and low cabinets consolidate storage along the edge.',cabinet),part('floor','Spatial sequence','A detail study of connected rooms, not a reconstruction of the complete apartment.',floor)],setExplode(n){portals.position.z=-n*.5;cabinet.position.x=-n*.7;screen.position.z=n*.6;track.position.y=n*.45},setRoof(v){screen.visible=v;track.visible=v},setDetail(n){screen.position.x=n/100*2.1}};
}
